import java.util.Scanner;
class Person{
    String name;
    int Seqno;
    Person(String _name, int _Seqno){
        name = _name;
        Seqno = _Seqno;
    }
}

public class JosephCircle {
    public static void main(String[] args){
        //TODO Autogeneratedethod stub
        Scanner scanner = new Scanner(System.in);
        System.out.println("------------请输入总人数------------");
        int totalNumber = scanner.nextInt();
        System.out.println("-----------请输入报数的大小----------");
        int outNum = scanner.nextInt();
        String [] name = new String [totalNumber];
        System.out.println("---------请输入"+totalNumber+"个人的名字,以回车键结束--------");
        for(int i = 0; i < totalNumber+1; i++){
            String str = scanner.nextLine();
            if(i == 0){
                continue;
            }
            name[i-1] = str;
            scanner.close();
            JosephCircle(totalNumber, outNum, name);
        }
    }
    private static void JosephCircle(int totalNum, int outNum, String[] name){
        Person [] ps = new Person[totalNum];
        for(int i = 0; i < totalNum; i++){
            Person p = new Person(name[i], i+1);
            ps[i] = p;
        }
        int pre = 0;
        int currentNum = totalNum;
        while(currentNum > 0){
            pre = (pre + outNum -1) % currentNum;
            System.out.println("--------------------"+ps[pre].Seqno+"号已出局--------------------");
            ps = adjust(ps, pre, currentNum);
            currentNum--;
        }
    }
    private static Person[] adjust(Person[] ps, int pre, int currentNum){
        for(int i = pre; i < currentNum-1; i++){
            ps[i] = ps[i+1];
        }
        return ps;
    }
}
